from __future__ import annotations

from pathlib import Path
import argparse
import json

import numpy as np
import pandas as pd
import yaml


ROOT = Path(__file__).resolve().parents[1]
CASE = ROOT / "cases" / "cow_luisi_mvp"


def parse_factors(values: list[str]) -> list[float]:
    factors: list[float] = []
    for value in values:
        for token in value.split(","):
            token = token.strip()
            if token:
                factors.append(float(token))
    if not factors:
        raise ValueError("At least one RICA multiplier is required.")
    return factors


def face_area_cm2(face_map: dict, face: str) -> float:
    info = face_map[face]
    if "area_mm2_measured" in info:
        return float(info["area_mm2_measured"]) * 0.01
    if "area_mm2_expected" in info:
        return float(info["area_mm2_expected"]) * 0.01
    raise KeyError(f"No area field found for {face}")


def summarize(values: pd.Series) -> dict[str, float]:
    arr = values.astype(float)
    return {
        "mean": float(arr.mean()),
        "min": float(arr.min()),
        "max": float(arr.max()),
        "peak_abs": float(arr.abs().max()),
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Rapid first-order RICA sensitivity estimate using inlet waveforms, "
            "outlet RCR conductances, and outlet cap areas. This is not a 3D CFD solve."
        )
    )
    parser.add_argument(
        "--factors",
        nargs="+",
        default=["0.50,0.70,0.85,1.00,1.15,1.30,1.50"],
        help="RICA flow/velocity multipliers, separated by spaces or commas.",
    )
    parser.add_argument(
        "--out-dir",
        default=str(CASE / "results" / "quick_rica_sensitivity"),
        help="Output directory for CSV and JSON reports.",
    )
    parser.add_argument(
        "--waveforms",
        default=str(CASE / "bc" / "simulated_ultrasound_inputs.csv"),
        help="Input waveform CSV generated by scripts/05_generate_inlet_waveforms.py.",
    )
    parser.add_argument(
        "--inlet-summary",
        default=str(CASE / "bc" / "inlet_summary.csv"),
        help="Inlet summary CSV generated by scripts/05_generate_inlet_waveforms.py.",
    )
    parser.add_argument(
        "--rcr-values",
        default=str(CASE / "bc" / "rcr_values.csv"),
        help="Outlet RCR table generated by scripts/06_generate_rcr_table.py.",
    )
    parser.add_argument(
        "--face-map",
        default=str(CASE / "geometry" / "face_map.json"),
        help="Face metadata with measured outlet cap areas.",
    )
    args = parser.parse_args()

    factors = parse_factors(args.factors)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    cfg = yaml.safe_load((ROOT / "config" / "case_luisi.yaml").read_text())
    inlets = list(cfg["faces"]["inlets"])
    outlets = list(cfg["faces"]["outlets"])

    waveforms = pd.read_csv(args.waveforms)
    inlet_summary = pd.read_csv(args.inlet_summary).set_index("name")
    rcr = pd.read_csv(args.rcr_values).set_index("face")
    face_map = json.loads(Path(args.face_map).read_text())

    missing = [name for name in inlets if f"{name}_flow_cm3_s" not in waveforms.columns]
    if missing:
        raise KeyError(f"Missing inlet waveform columns: {missing}")

    outlet_conductance = {}
    outlet_area = {}
    for face in outlets:
        resistance = float(rcr.loc[face, "Rp_dyn_s_cm5"]) + float(rcr.loc[face, "Rd_dyn_s_cm5"])
        outlet_conductance[face] = 1.0 / resistance
        outlet_area[face] = face_area_cm2(face_map, face)
    conductance_sum = sum(outlet_conductance.values())
    outlet_weights = {face: outlet_conductance[face] / conductance_sum for face in outlets}

    rows = []
    ts_frames = []
    baseline_rica_mean_velocity = float(inlet_summary.loc["RICA", "mean_velocity_cm_s"])
    baseline_rica_mean_flow = float(inlet_summary.loc["RICA", "mean_flow_cm3_s"])

    for factor in factors:
        scenario = waveforms[["time_s"]].copy()
        for inlet in inlets:
            col = f"{inlet}_flow_cm3_s"
            scenario[col] = waveforms[col].astype(float)
        scenario["RICA_flow_cm3_s"] = waveforms["RICA_flow_cm3_s"].astype(float) * factor
        scenario["total_inlet_flow_cm3_s"] = sum(scenario[f"{name}_flow_cm3_s"] for name in inlets)

        scenario_rows = {
            "rica_multiplier": factor,
            "RICA_mean_velocity_cm_s": baseline_rica_mean_velocity * factor,
            "RICA_mean_flow_cm3_s": baseline_rica_mean_flow * factor,
            "total_inlet_mean_flow_cm3_s": float(scenario["total_inlet_flow_cm3_s"].mean()),
            "total_inlet_mean_flow_mL_min": float(scenario["total_inlet_flow_cm3_s"].mean() * 60.0),
        }

        for face in outlets:
            q_col = f"{face}_estimated_flow_cm3_s"
            v_col = f"{face}_estimated_mean_velocity_cm_s"
            scenario[q_col] = scenario["total_inlet_flow_cm3_s"] * outlet_weights[face]
            scenario[v_col] = scenario[q_col] / outlet_area[face]

            q_stats = summarize(scenario[q_col])
            v_stats = summarize(scenario[v_col])
            scenario_rows[f"{face}_flow_mean_cm3_s"] = q_stats["mean"]
            scenario_rows[f"{face}_velocity_mean_cm_s"] = v_stats["mean"]
            scenario_rows[f"{face}_velocity_peak_cm_s"] = v_stats["peak_abs"]

        scenario["rica_multiplier"] = factor
        ts_frames.append(scenario)
        rows.append(scenario_rows)

    summary = pd.DataFrame(rows)
    summary_path = out_dir / "rica_sweep_summary.csv"
    timeseries_path = out_dir / "rica_sweep_timeseries.csv"
    summary.to_csv(summary_path, index=False)
    pd.concat(ts_frames, ignore_index=True).to_csv(timeseries_path, index=False)

    baseline = summary[np.isclose(summary["rica_multiplier"], 1.0)]
    slopes = []
    for face in outlets:
        y = summary[f"{face}_velocity_mean_cm_s"].to_numpy(dtype=float)
        x = summary["RICA_mean_velocity_cm_s"].to_numpy(dtype=float)
        slope, intercept = np.polyfit(x, y, deg=1)
        corr = np.corrcoef(x, y)[0, 1]
        base_value = float(baseline[f"{face}_velocity_mean_cm_s"].iloc[0]) if not baseline.empty else float("nan")
        slopes.append(
            {
                "face": face,
                "velocity_slope_cm_s_per_RICA_cm_s": float(slope),
                "intercept_cm_s": float(intercept),
                "pearson_r_across_sweep": float(corr),
                "baseline_velocity_mean_cm_s": base_value,
                "outlet_flow_weight": float(outlet_weights[face]),
                "outlet_area_cm2": float(outlet_area[face]),
            }
        )
    slope_df = pd.DataFrame(slopes)
    slope_path = out_dir / "rica_to_outlet_velocity_relationship.csv"
    slope_df.to_csv(slope_path, index=False)

    assessment = {
        "method": "rapid_0d_boundary_surrogate",
        "is_3d_navier_stokes_solve": False,
        "requires_new_svmultiphysics_solve": False,
        "interpretation": (
            "This estimates outlet-level Willis/branch velocity response by distributing "
            "total inlet flow according to normalized outlet RCR conductance. It is useful "
            "for immediate direction and sensitivity screening, but it does not resolve "
            "internal CoW segment velocities, recirculation, pressure-wave transients, or "
            "collateral redistribution caused by 3D geometry."
        ),
        "when_solve_is_required": [
            "Quantitative 3D velocity/pressure/WSS fields.",
            "Velocity inside A1/ACom/PCom/P1/M1 or any internal section not represented by an outlet cap.",
            "Effects of local geometry, flow separation, secondary flow, stenosis, asymmetry, or transient inertia.",
            "Publication-quality patient-specific hemodynamic conclusions.",
        ],
        "inputs": {
            "waveforms": str(Path(args.waveforms).relative_to(ROOT)),
            "inlet_summary": str(Path(args.inlet_summary).relative_to(ROOT)),
            "rcr_values": str(Path(args.rcr_values).relative_to(ROOT)),
            "face_map": str(Path(args.face_map).relative_to(ROOT)),
            "rica_multipliers": factors,
        },
        "outputs": {
            "summary": str(summary_path.relative_to(ROOT)),
            "timeseries": str(timeseries_path.relative_to(ROOT)),
            "relationship": str(slope_path.relative_to(ROOT)),
        },
    }
    assessment_path = out_dir / "quick_assessment.json"
    assessment_path.write_text(json.dumps(assessment, indent=2))

    print("Wrote", summary_path.relative_to(ROOT))
    print("Wrote", timeseries_path.relative_to(ROOT))
    print("Wrote", slope_path.relative_to(ROOT))
    print("Wrote", assessment_path.relative_to(ROOT))
    print("\nEstimated RICA-to-outlet mean velocity relationship:")
    print(slope_df.to_string(index=False))


if __name__ == "__main__":
    main()
